# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request:
    branches: [ master, develop, staging ]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v2
      - name: Using Node.js v14.16
        uses: actions/setup-node@v1
        with:
          node-version: 14.16
      - name: npm install and test
        run: |
          cd frontend
          npm install
          npm test

  build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v2
      - name: Using Node.js v14.16
        uses: actions/setup-node@v1
        with:
          node-version: 14.16
      - name: npm install and test
        run: |
          cd frontend
          npm install
          npm test