# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Pull Request CI

on:
  pull_request:
    branches: [ master, develop, staging ]

jobs:
  verify-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js v14.16
        uses: actions/setup-node@v1
        with:
          node-version: 14.16
      - name: Install dependencies
        run: npm install
      - name: Typescript Compilation Check
        run: yarn typecheck
      - name: ESLinting Check
        run: yarn lint
      - name: Tests Check
        run: yarn test
      - uses: actions/upload-artifact@v2
        with:
          name: Upload test coverage
          path: coverage/*
  verify-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js v14.16
        uses: actions/setup-node@v1
        with:
          node-version: 14.16
      - name: Install dependencies
        run: npm install
      - name: Typescript Compilation Check
        run: yarn typecheck
      - name: ESLinting Check
        run: yarn lint
      - name: Tests Check
        run: yarn test
      - name: ls
        run: ls coverage
      - uses: actions/upload-artifact@v2
        with:
          name: Upload test coverage
          path: coverage/*
